# Generated by Django 3.1 on 2020-08-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200809_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='thumb',
            field=models.ImageField(default='job_thumb/default.jpg', upload_to='job_thumb'),
        ),
    ]
