# Generated by Django 3.1 on 2020-08-14 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_personalinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalInfo',
            new_name='Personal',
        ),
    ]
